name: Build RISC-V Doc Spec Template

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Pull the latest RISC-V Docs container image
    # https://github.com/riscv/riscv-docs-base-container-image
    # https://hub.docker.com/r/riscvintl/riscv-docs-base-container-image
    - name: Pull Container
      run: |
        docker pull riscvintl/riscv-docs-base-container-image:latest
    # Build PDF file using the container
    - name: Build Files
      run: |
        docker run --rm -v ${{ github.workspace }}:/build riscvintl/riscv-docs-base-container-image:latest \
        /bin/sh -c 'make'
    # Set the short SHA for use in artifact names
    - name: Set short SHA
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

    # Upload the built PDF file as artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: spec-sample-${{ env.SHORT_SHA }}.pdf
        path: ${{ github.workspace }}/spec-sample.pdf
        retention-days: 7
