---
name: RISC-V ISA Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: Create a new RISC-V ISA release if set to true
        required: false
        default: 'false'
      tag_name:
        description: Name of the tag for the release
        required: true
      release_notes:
        description: Release Notes
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

    # Set the short SHA for use in artifact names
      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

    # Get the current date
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update environment variables for push events
        run: |
          echo "EXTRA_ASCIIDOC_OPTIONS=-a github_commit_sha=$GITHUB_SHA" >> "$GITHUB_ENV"
        if: github.event_name == 'push'

      - name: Update environment variables for manual workflow trigger
        run: |
          echo "RELEASE_TYPE=intermediate" >> "$GITHUB_ENV"
        if: github.event.inputs.create_release == 'true'

    # Build PDF and HTML files using the container
      - name: Build Files
        id: build_files
        run: make -j$(nproc)

      # Upload the riscv-cheri PDF file
      - name: Upload riscv-cheri.pdf
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-cheri-${{ env.SHORT_SHA }}.pdf
          path: ${{ github.workspace }}/build/riscv-cheri.pdf
          retention-days: 7
      - name: Upload riscv-cheri.html
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-cheri-${{ env.SHORT_SHA }}.html
          path: ${{ github.workspace }}/build/riscv-cheri.html
          retention-days: 7
      - name: Upload riscv-cheri.epub
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-cheri-${{ env.SHORT_SHA }}.epub
          path: ${{ github.workspace }}/build/riscv-cheri.epub
          retention-days: 7

    # Upload the riscv-privileged PDF file
      - name: Upload riscv-privileged.pdf
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-privileged-${{ env.SHORT_SHA }}.pdf
          path: ${{ github.workspace }}/build/riscv-privileged.pdf
          retention-days: 7

    # Upload the riscv-privileged HTML file
      - name: Upload riscv-privileged.html
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-privileged-${{ env.SHORT_SHA }}.html
          path: ${{ github.workspace }}/build/riscv-privileged.html
          retention-days: 7

    # Upload the riscv-privileged EPUB file
      - name: Upload riscv-privileged.epub
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-privileged-${{ env.SHORT_SHA }}.epub
          path: ${{ github.workspace }}/build/riscv-privileged.epub
          retention-days: 7

    # Upload the riscv-unprivileged PDF file
      - name: Upload riscv-unprivileged.pdf
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-unprivileged-${{ env.SHORT_SHA }}.pdf
          path: ${{ github.workspace }}/build/riscv-unprivileged.pdf
          retention-days: 7

    # Upload the riscv-unprivileged HTML file
      - name: Upload riscv-unprivileged.html
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-unprivileged-${{ env.SHORT_SHA }}.html
          path: ${{ github.workspace }}/build/riscv-unprivileged.html
          retention-days: 7

    # Upload the riscv-unprivileged EPUB file
      - name: Upload riscv-unprivileged.epub
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: riscv-unprivileged-${{ env.SHORT_SHA }}.epub
          path: ${{ github.workspace }}/build/riscv-unprivileged.epub
          retention-days: 7

      - name: Create Release
        if: steps.build_files.outcome == 'success' && github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true'
        #uses: softprops/action-gh-release@v2.2.2
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          draft: false
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ env.CURRENT_DATE }}
          body: |
            This release was created by: ${{ github.event.sender.login }}
            Release Notes: ${{ github.event.inputs.release_notes }}
          files: |
            ${{ github.workspace }}/build/riscv-cheri.pdf
            ${{ github.workspace }}/build/riscv-cheri.html
            ${{ github.workspace }}/build/riscv-cheri.epub
            ${{ github.workspace }}/build/riscv-privileged.pdf
            ${{ github.workspace }}/build/riscv-privileged.html
            ${{ github.workspace }}/build/riscv-privileged.epub
            ${{ github.workspace }}/build/riscv-unprivileged.pdf
            ${{ github.workspace }}/build/riscv-unprivileged.html
            ${{ github.workspace }}/build/riscv-unprivileged.epub
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}

    # Create directory structure pages sites for privileged and unprivileged specs.
      - name: Make GitHub pages directory
        run: |
          mkdir -p dist/snapshot/unprivileged dist/snapshot/privileged
          cp build/riscv-unprivileged.html dist/snapshot/unprivileged/index.html
          cp build/riscv-privileged.html dist/snapshot/privileged/index.html
          cp build/riscv-cheri.html dist/index.html
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

  # Deploy HTML to GitHub pages.
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
